### ISSUE TITLE
Updating the Kabanero logging guide for OCP 4.2

### ISSUE THREAD

**Issue by fwji** [kabanero-io/guide-app-logging#14]
1. Use operator hub to install cluster logging operator and elasticsearch operator instead of using the ansible playbook as in 3.11

**Comment by SueChaplain** [comment]
There is a new guide for app logging with OCP: https://kabanero.io/guides/app-logging-ocp-4-2/
Source for this guide is in the **guides** repository in the /publish folder. Any new issues should be raised against that repo. Closing.
